"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "en" | "vi" | "ko" | "zh"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    tournaments: "Tournaments",
    players: "Players",
    leaderboard: "Leaderboard",
    profile: "Profile",
    admin: "Admin",
    register: "Register",
    login: "Login",
    ongoing: "Ongoing",
    upcoming: "Upcoming",
    finished: "Finished",
    search: "Search tournaments...",
    region: "Region",
    status: "Status",
    view: "View",
    register_now: "Register Now",
    tournament_details: "Tournament Details",
    player_registration: "Player Registration",
    scoreboard: "Scoreboard",
    admin_dashboard: "Admin Dashboard",
    create_tournament: "Create Tournament",
    edit_tournament: "Edit Tournament",
    manage_players: "Manage Players",
    settings: "Settings",
    all_tournaments: "All Tournaments",
    my_tournaments: "My Tournaments",
    tournament_name: "Tournament Name",
    description: "Description",
    start_date: "Start Date",
    end_date: "End Date",
    registration_deadline: "Registration Deadline",
    max_players: "Maximum Players",
    rounds: "Rounds",
    matches_per_round: "Matches per Round",
    point_system: "Point System",
    elimination_rule: "Elimination Rule",
    budget: "Budget",
    registration_fee: "Registration Fee",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    confirm: "Confirm",
    summoner_name: "Summoner Name",
    select_region: "Select Region",
    search_summoner: "Search Summoner",
    register_for_tournament: "Register for Tournament",
    tournament_schedule: "Tournament Schedule",
    tournament_format: "Tournament Format",
    current_round: "Current Round",
    total_rounds: "Total Rounds",
    matches_per_round_short: "Matches per Round",
    elimination_rule_short: "Elimination Rule",
    registered_players: "Registered Players",
    player_list: "Player List",
    round_results: "Round Results",
    match_history: "Match History",
    statistics: "Statistics",
    performance: "Performance",
    placement: "Placement",
    points: "Points",
    total_score: "Total Score",
    rank: "Rank",
    status: "Status",
    advanced: "Advanced",
    eliminated: "Eliminated",
    lobby: "Lobby",
    match: "Match",
    date: "Date",
    time: "Time",
    region_short: "Region",
    player: "Player",
    action: "Action",
    sync_matches: "Sync Matches",
    assign_lobbies: "Assign Lobbies",
    recalculate_points: "Recalculate Points",
    advance_round: "Advance Round",
    export_scoreboard: "Export Scoreboard",
    live_updates: "Live Updates",
    syncing: "Syncing...",
    sync_error: "Sync Error",
    not_synced: "Not Synced",
    operational: "Operational",
    api_status: "API Status",
    last_checked: "Last checked",
    minutes_ago: "minutes ago",
    active_tournaments: "Active Tournaments",
    total_players: "Total Players",
    total_tournaments: "Total Tournaments",
    registration: "Registration",
    progress: "Progress",
    last_sync: "Last sync",
    success: "Success",
    idle: "Idle",
    error: "Error",
  },
  vi: {
    home: "Trang chủ",
    tournaments: "Giải đấu",
    players: "Người chơi",
    leaderboard: "Bảng xếp hạng",
    profile: "Hồ sơ",
    admin: "Quản trị",
    register: "Đăng ký",
    login: "Đăng nhập",
    ongoing: "Đang diễn ra",
    upcoming: "Sắp diễn ra",
    finished: "Đã kết thúc",
    search: "Tìm giải đấu...",
    region: "Khu vực",
    status: "Trạng thái",
    view: "Xem",
    register_now: "Đăng ký ngay",
    tournament_details: "Chi tiết giải đấu",
    player_registration: "Đăng ký người chơi",
    scoreboard: "Bảng điểm",
    admin_dashboard: "Bảng điều khiển quản trị",
    create_tournament: "Tạo giải đấu",
    edit_tournament: "Chỉnh sửa giải đấu",
    manage_players: "Quản lý người chơi",
    settings: "Cài đặt",
    all_tournaments: "Tất cả giải đấu",
    my_tournaments: "Giải đấu của tôi",
    tournament_name: "Tên giải đấu",
    description: "Mô tả",
    start_date: "Ngày bắt đầu",
    end_date: "Ngày kết thúc",
    registration_deadline: "Hạn đăng ký",
    max_players: "Số người chơi tối đa",
    rounds: "Vòng đấu",
    matches_per_round: "Số trận mỗi vòng",
    point_system: "Hệ thống điểm",
    elimination_rule: "Quy tắc loại",
    budget: "Ngân sách",
    registration_fee: "Phí đăng ký",
    save: "Lưu",
    cancel: "Hủy",
    delete: "Xóa",
    confirm: "Xác nhận",
    summoner_name: "Tên triệu hồi",
    select_region: "Chọn khu vực",
    search_summoner: "Tìm kiếm triệu hồi",
    register_for_tournament: "Đăng ký giải đấu",
    tournament_schedule: "Lịch giải đấu",
    tournament_format: "Định dạng giải đấu",
    current_round: "Vòng hiện tại",
    total_rounds: "Tổng số vòng",
    matches_per_round_short: "Số trận mỗi vòng",
    elimination_rule_short: "Quy tắc loại",
    registered_players: "Người chơi đã đăng ký",
    player_list: "Danh sách người chơi",
    round_results: "Kết quả vòng đấu",
    match_history: "Lịch sử trận đấu",
    statistics: "Thống kê",
    performance: "Hiệu suất",
    placement: "Vị trí",
    points: "Điểm",
    total_score: "Tổng điểm",
    rank: "Xếp hạng",
    status: "Trạng thái",
    advanced: "Đã tiến",
    eliminated: "Đã loại",
    lobby: "Phòng đấu",
    match: "Trận đấu",
    date: "Ngày",
    time: "Thời gian",
    region_short: "Khu vực",
    player: "Người chơi",
    action: "Hành động",
    sync_matches: "Đồng bộ trận đấu",
    assign_lobbies: "Phân phòng đấu",
    recalculate_points: "Tính lại điểm",
    advance_round: "Tiến vòng đấu",
    export_scoreboard: "Xuất bảng điểm",
    live_updates: "Cập nhật trực tiếp",
    syncing: "Đang đồng bộ...",
    sync_error: "Lỗi đồng bộ",
    not_synced: "Chưa đồng bộ",
    operational: "Hoạt động",
    api_status: "Trạng thái API",
    last_checked: "Kiểm tra lần cuối",
    minutes_ago: "phút trước",
    active_tournaments: "Giải đấu đang diễn ra",
    total_players: "Tổng số người chơi",
    total_tournaments: "Tổng số giải đấu",
    registration: "Đăng ký",
    progress: "Tiến độ",
    last_sync: "Đồng bộ lần cuối",
    success: "Thành công",
    idle: "Chờ",
    error: "Lỗi",
  },
  ko: {
    home: "홈",
    tournaments: "토너먼트",
    players: "플레이어",
    leaderboard: "리더보드",
    profile: "프로필",
    admin: "관리자",
    register: "등록",
    login: "로그인",
    ongoing: "진행 중",
    upcoming: "예정",
    finished: "종료",
    search: "토너먼트 검색...",
    region: "지역",
    status: "상태",
    view: "보기",
    register_now: "지금 등록",
    tournament_details: "토너먼트 상세",
    player_registration: "플레이어 등록",
    scoreboard: "점수판",
    admin_dashboard: "관리자 대시보드",
    create_tournament: "토너먼트 생성",
    edit_tournament: "토너먼트 편집",
    manage_players: "플레이어 관리",
    settings: "설정",
    all_tournaments: "모든 토너먼트",
    my_tournaments: "내 토너먼트",
    tournament_name: "토너먼트 이름",
    description: "설명",
    start_date: "시작일",
    end_date: "종료일",
    registration_deadline: "등록 마감일",
    max_players: "최대 플레이어 수",
    rounds: "라운드",
    matches_per_round: "라운드당 매치 수",
    point_system: "포인트 시스템",
    elimination_rule: "탈락 규칙",
    budget: "예산",
    registration_fee: "등록비",
    save: "저장",
    cancel: "취소",
    delete: "삭제",
    confirm: "확인",
    summoner_name: "소환사 이름",
    select_region: "지역 선택",
    search_summoner: "소환사 검색",
    register_for_tournament: "토너먼트 등록",
    tournament_schedule: "토너먼트 일정",
    tournament_format: "토너먼트 형식",
    current_round: "현재 라운드",
    total_rounds: "총 라운드",
    matches_per_round_short: "라운드당 매치",
    elimination_rule_short: "탈락 규칙",
    registered_players: "등록된 플레이어",
    player_list: "플레이어 목록",
    round_results: "라운드 결과",
    match_history: "매치 기록",
    statistics: "통계",
    performance: "성과",
    placement: "배치",
    points: "포인트",
    total_score: "총점",
    rank: "순위",
    status: "상태",
    advanced: "진출",
    eliminated: "탈락",
    lobby: "로비",
    match: "매치",
    date: "날짜",
    time: "시간",
    region_short: "지역",
    player: "플레이어",
    action: "액션",
    sync_matches: "매치 동기화",
    assign_lobbies: "로비 배정",
    recalculate_points: "포인트 재계산",
    advance_round: "라운드 진행",
    export_scoreboard: "점수판 내보내기",
    live_updates: "실시간 업데이트",
    syncing: "동기화 중...",
    sync_error: "동기화 오류",
    not_synced: "동기화되지 않음",
    operational: "작동 중",
    api_status: "API 상태",
    last_checked: "마지막 확인",
    minutes_ago: "분 전",
    active_tournaments: "활성 토너먼트",
    total_players: "총 플레이어",
    total_tournaments: "총 토너먼트",
    registration: "등록",
    progress: "진행",
    last_sync: "마지막 동기화",
    success: "성공",
    idle: "대기",
    error: "오류",
  },
  zh: {
    home: "首页",
    tournaments: "比赛",
    players: "玩家",
    leaderboard: "排行榜",
    profile: "个人资料",
    admin: "管理员",
    register: "注册",
    login: "登录",
    ongoing: "进行中",
    upcoming: "即将到来",
    finished: "已结束",
    search: "搜索比赛...",
    region: "地区",
    status: "状态",
    view: "查看",
    register_now: "立即注册",
    tournament_details: "比赛详情",
    player_registration: "玩家注册",
    scoreboard: "记分板",
    admin_dashboard: "管理员仪表板",
    create_tournament: "创建比赛",
    edit_tournament: "编辑比赛",
    manage_players: "管理玩家",
    settings: "设置",
    all_tournaments: "所有比赛",
    my_tournaments: "我的比赛",
    tournament_name: "比赛名称",
    description: "描述",
    start_date: "开始日期",
    end_date: "结束日期",
    registration_deadline: "注册截止日期",
    max_players: "最大玩家数",
    rounds: "轮次",
    matches_per_round: "每轮比赛数",
    point_system: "积分系统",
    elimination_rule: "淘汰规则",
    budget: "预算",
    registration_fee: "注册费",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    confirm: "确认",
    summoner_name: "召唤师名称",
    select_region: "选择地区",
    search_summoner: "搜索召唤师",
    register_for_tournament: "注册比赛",
    tournament_schedule: "比赛日程",
    tournament_format: "比赛格式",
    current_round: "当前轮次",
    total_rounds: "总轮次",
    matches_per_round_short: "每轮比赛",
    elimination_rule_short: "淘汰规则",
    registered_players: "已注册玩家",
    player_list: "玩家列表",
    round_results: "轮次结果",
    match_history: "比赛历史",
    statistics: "统计",
    performance: "表现",
    placement: "名次",
    points: "积分",
    total_score: "总分",
    rank: "排名",
    status: "状态",
    advanced: "晋级",
    eliminated: "淘汰",
    lobby: "大厅",
    match: "比赛",
    date: "日期",
    time: "时间",
    region_short: "地区",
    player: "玩家",
    action: "操作",
    sync_matches: "同步比赛",
    assign_lobbies: "分配大厅",
    recalculate_points: "重新计算积分",
    advance_round: "进入下一轮",
    export_scoreboard: "导出记分板",
    live_updates: "实时更新",
    syncing: "同步中...",
    sync_error: "同步错误",
    not_synced: "未同步",
    operational: "运行中",
    api_status: "API状态",
    last_checked: "上次检查",
    minutes_ago: "分钟前",
    active_tournaments: "活跃比赛",
    total_players: "总玩家数",
    total_tournaments: "总比赛数",
    registration: "注册",
    progress: "进度",
    last_sync: "上次同步",
    success: "成功",
    idle: "空闲",
    error: "错误",
  },
}

const LanguageContext = createContext<LanguageContextType | null>(null)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}
